lst = [1, 2, 3]
lst.append(4)
print("After append:", lst)
lst.extend([5, 7])
print("After extend:", lst)
lst.insert(5, 6)
print("After insert:", lst)
lst.remove(6)
print("after removing:", lst)
lst.pop()
print("pop: ",lst)
print(lst.index(1))
lst.count(1)
print("count:", lst)
lst.sort()
print("sort: ",lst)
lst.reverse()
print("reverse: ",lst)

#tuple immutable
tup=(1,2,3)
print("tuple length")
print(len(tup))
print("index:",tup.index(2))
print("count:",tup.count(3))
print("min:",min(tup))
print("sum:",sum(tup))